export const GET_ALL_GAMES = "GET_ALL_GAMES";
export const GET_GENRES = "GET_GENRES";
export const FILTER_GAMES_BY_GENRES = "FILTER_GAMES_BY_GENRES";
export const FILTER_BY_ORIGIN = "FILTER_BY_ORIGIN";
export const ORDER_BY_NAME = "ORDER_BY_NAME";
export const ORDER_BY_RATING = "ORDER_BY_RATING";
export const GET_GAME_BY_NAME = "GET_GAME_BY_NAME";
export const CREATE_VIDEOGAME = "CREATE_VIDEOGAME";
export const GET_PLATFORMS = "GET_PLATFORMS";
export const GET_DETAIL = "GET_DETAIL";


export const ADD_TO_CART=
"ADD_TO_CART";

export const REMOVE_ONE_FROM_CART="REMOVE_ONE_FROM_FROM_CART";

export const REMOVE_ALL_FROM_CART="REMOVE_ALL_FROM_CART";

export const CLEAR_CART="CLEAR_CART";




